# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool: 
  name: Default
#  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: CmdLine@2
  inputs:
    script: 'yarn install'
- task: CmdLine@2
  inputs:
    script: 'npm install -g node-gyp'
- task: CmdLine@2
  inputs:
    script: 'yarn run build:npm'
- task: CmdLine@2
  inputs:
    script: 'cd main'
- task: CmdLine@2
  inputs:
    script: 'yarn install'
- task: CmdLine@2
  inputs:
    script: 'yarn run build'
- task: CmdLine@2
  inputs:
    script: 'cd ..'
- task: CmdLine@2
  inputs:
    script: 'npm install copyfiles -g'
- task: CmdLine@2
  inputs:
    script: 'yarn run copyfiles'
- task: CmdLine@2
  inputs:
    script: 'yarn run dist'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'dist/win-unpacked'
    publishLocation: 'pipeline'