export const languageList = [
    { id: 'en-US', name: 'ENGLISH' },
    { id: 'en-ES', name: 'ESPAÑOL' },
    { id: 'en-FR', name: 'FRANÇAIS' },
    { id: 'en-DE', name: 'DEUTSCH' },
    { id: 'en-NL', name: 'NEDERLANDS' },
    { id: 'en-IT', name: 'ITALIANO' },
    { id: 'en-PT', name: 'PORTUGUÊS' },
    { id: 'en-DK', name: 'DANSK' },
    { id: 'en-NO', name: 'NORSK' },
    { id: 'en-SE', name: 'SVENSKA' },
    { id: 'en-FI', name: 'SUOMI' },
    { id: 'en-EE', name: 'EESTI KEEL' },
    { id: 'en-LV', name: 'LATVIEŠU' },
    { id: 'en-LT', name: 'LIETUVIŲ K' },
    { id: 'en-PL', name: 'POLSKI' },
    { id: 'en-CZ', name: 'ČEŠTINA' },
    { id: 'en-SZ', name: 'SLOVENSKY' },
    { id: 'en-HU', name: 'MAGYAR' },
    { id: 'en-RO', name: 'ROMÂNĂ' },
    { id: 'en-RU', name: 'РУССКИЙ' },
    { id: 'en-UA', name: 'УКРАЇНСЬКА' },
    { id: 'en-KZ', name: 'ҚАЗАҚША' },
    { id: 'en-TR', name: 'TÜRK' },
    { id: 'en-GR', name: 'ΕΛΛΗΝΙΚΆ' },
    { id: 'en-AD', name: 'العربية' },
    { id: 'zh-TW', name: '繁體中文'},
    { id: 'zh-CN', name: '简体中文'},
    { id: 'en-KR', name: '한국어' },
    { id: 'en-JP', name: '日本語'},
]